const PROJECT_ID =
  process.env.GCP_PROJECT ||
  process.env.GOOGLE_CLOUD_PROJECT ||
  'extended-byway-454621-s6';
const DATASET = process.env.BIGQUERY_DATASET || 'sp500data1';
const NEWSLETTER_TABLE = process.env.BIGQUERY_NEWSLETTER_TABLE || 'weekly_newsletter';
const SUBSCRIPTIONS_TABLE = process.env.BIGQUERY_NEWSLETTER_SUBSCRIPTIONS_TABLE || 'newsletter_subscriptions';
const NOTIFICATIONS_TABLE = process.env.BIGQUERY_USER_NOTIFICATIONS_TABLE || 'user_notifications';

const NEWSLETTER_TABLE_FQN = `${PROJECT_ID}.${DATASET}.${NEWSLETTER_TABLE}`;
const SUBSCRIPTIONS_TABLE_FQN = `${PROJECT_ID}.${DATASET}.${SUBSCRIPTIONS_TABLE}`;
const NOTIFICATIONS_TABLE_FQN = `${PROJECT_ID}.${DATASET}.${NOTIFICATIONS_TABLE}`;

module.exports = {
  PROJECT_ID,
  DATASET,
  NEWSLETTER_TABLE,
  SUBSCRIPTIONS_TABLE,
  NOTIFICATIONS_TABLE,
  NEWSLETTER_TABLE_FQN,
  SUBSCRIPTIONS_TABLE_FQN,
  NOTIFICATIONS_TABLE_FQN
};
